# 4 · Working with data, and drawing it
# Statistics for brain and cognitive sciences (CN2) -- 2026/27
# student script
#
# GENERATED FROM sessions/04-working-with-data/index.qmd -- DO NOT EDIT THIS FILE.
# Edit the .qmd and re-render the website; this file is overwritten.
#
# Open the .Rproj in this folder first, so that "data/..." paths resolve.

# 
# Optional extra practice, and unlike practicals 1 to 3 this one runs alongside no
# lecture at all. It covers the handling and plotting that Prof. Noventa's
# analysis scripts assume you already know, and that the Introduction to R
# lectures do not cover. Nothing here is assessed.
# 
# ---- What you will be able to do -----------------------------------------------
# 
# By the end of this practical you should be able to:
# 
# - pull out the rows and columns you want, and sort a table;
# - create a new variable by recoding an existing one;
# - set the **order of a factor's levels**, and say why that changes a model;
# - summarise a variable within each diagnostic group;
# - draw a histogram, a boxplot and a scatterplot, with axes a reader can
#   understand;
# - turn a wide table into a long one, which is the shape repeated-measures
#   analyses need.
# 
# ---- [⬇ Download this practical](../../handouts/04-working-with-data.zip) ------
# 
# A zip containing the R script, the data, and an `.Rproj` file. Unzip it
# somewhere you can find again, then double-click the `.Rproj`.
# 
# ---- Before you start ----------------------------------------------------------
# 
# Double-click the `.Rproj` file in this folder. If you see
# `cannot open file 'data/memclinic.csv'`, run `getwd()` — you opened the script
# rather than the project.
# 
# Ctrl+Enter (Cmd+Enter on a Mac) runs the current line. The *Source* button will
# fail on the whole file while any `___` blank is still unfilled.
# 
# We call dplyr and psych functions with the pkg::fun() form rather than
# loading them, so it is always obvious where a function came from.
memclinic <- read.csv("data/memclinic.csv")
str(memclinic)

# 
# The [codebook](data/codebook.md) describes every column.
# 
# ---- Rows and columns ----------------------------------------------------------
# 
# Inside `[ ]`, what comes **before** the comma chooses rows and what comes
# **after** it chooses columns.
# 
memclinic[1:3, ]                                # first three people
memclinic[memclinic$group == "AD", ][1:3, ]     # the AD patients
head(memclinic[, c("id", "group", "moca")], 3)  # three columns

# 
# Asking for **one** column with a comma gives you a vector; asking for two gives
# you a data frame.
# 
class(memclinic[memclinic$group == "AD", "moca"])
class(memclinic[memclinic$group == "AD", c("id", "moca")])

# 
# This catches people when a function suddenly complains that it was given a
# vector where it wanted a table.
# 
# `subset()` says the same thing more readably:
# 
severe <- subset(memclinic, group == "AD" & moca < 20)
nrow(severe)

# 
# Note it takes bare column names, with no `memclinic$`. It is a convenience for
# interactive work; inside your own functions it can behave unexpectedly, so the
# `[ ]` form is the safer habit.
# 
# ---- Sorting -------------------------------------------------------------------
# 
# `order()` returns the *positions* that would put a vector in order, and you feed
# those back in as row numbers.
# 
smallest <- memclinic[order(memclinic$hippo_vol_mm3), ]
head(smallest[, c("id", "group", "hippo_vol_mm3")], 3)

largest <- memclinic[order(-memclinic$hippo_vol_mm3), ]
head(largest[, c("id", "group", "hippo_vol_mm3")], 3)

# 
# (`sort()` sorts a single vector; `order()` is what you need to reorder a whole
# table.)
# 
# ---- Making new variables ------------------------------------------------------
# 
# `ifelse()` works through a vector and returns one of two values for each element.
# 
memclinic$screen <- ifelse(memclinic$moca < 26, "below cut-off", "normal")
table(memclinic$screen)

# 
# For more than two outcomes, nested `ifelse()` becomes unreadable. The
# professor's tool for this is `case_when()`:
# 
memclinic$severity <- dplyr::case_when(
  memclinic$moca >= 26 ~ "normal",
  memclinic$moca >= 20 ~ "mild",
  TRUE                 ~ "moderate-severe"
)
table(memclinic$severity)

# 
# Conditions are checked **in the order you write them**, and the first match
# wins — which is why `>= 26` has to come before `>= 20`. The final `TRUE` is the
# catch-all.
# 
# ---- Factors, and why their order matters --------------------------------------
# 
# In practical 2 you saw that `group` arrives as text, and that making it a
# factor sorts the levels alphabetically:
# 
levels(factor(memclinic$group))

# 
# `AD` first. That is not how anyone would present these groups, and it is not
# harmless, because the **first level becomes the baseline** that everything else
# is compared against.
# 
coef(lm(moca ~ factor(group), data = memclinic))

# 
# The intercept, 19.18, is the *AD* mean. Now set the order deliberately:
# 
memclinic$group <- factor(memclinic$group, levels = c("HC", "MCI", "AD"))
levels(memclinic$group)

coef(lm(moca ~ group, data = memclinic))

# 
# The intercept is now 28.38, the **HC** mean, and the other two numbers are the
# MCI and AD *deficits* relative to healthy controls — which is what a clinical
# reader expects. Same data, same model, every number different.
# 
contrasts(memclinic$group)

# 
# That matrix is what R actually put into the model. Practical 6 is about nothing
# else.
# 
# `relevel()` moves one level to the front without retyping them all:
# 
levels(relevel(memclinic$group, ref = "AD"))

# 
# ---- Counting ------------------------------------------------------------------
# 
table(memclinic$group)
table(memclinic$group, memclinic$sex)
round(prop.table(table(memclinic$group, memclinic$screen), 1), 2)

# 
# `prop.table(..., 1)` turns counts into proportions **within each row**, so each
# row sums to 1.
# 
# ---- Summarising by group ------------------------------------------------------
# 
tapply(memclinic$moca, memclinic$group, mean)

# 
# `aggregate()` does the same with a formula, and handles several variables at
# once:
# 
aggregate(moca ~ group, data = memclinic, FUN = mean)
aggregate(cbind(hippo_vol_mm3, csf_ptau) ~ group, data = memclinic, FUN = mean)

# 
# `with()` saves repeating the data frame name:
# 
with(memclinic, tapply(hippo_vol_mm3, group, median))

# 
# The `psych` package gives a fuller description, including skewness:
# 
psych::describe(memclinic[, c("moca", "hippo_vol_mm3", "csf_ptau")])

# 
# Select the columns you want first. `psych::describe(memclinic)` will happily
# report a mean for `id` and `group`, marking them with a `*` — a number that
# means nothing. This is why the course scripts write
# `psych::describe(memclinic[, c("hippo_vol_mm3", "stroop_cost_ms")])` instead.
# 
# Look at `skew` for `csf_ptau`: strongly positive, so the distribution has a long
# right tail and its mean sits well above its median. The next section makes that
# visible.
# 
# ---- Drawing the data ----------------------------------------------------------
# 
# ---- One variable: a histogram -------------------------------------------------
# 
hist(memclinic$csf_ptau,
     breaks = 20,
     main   = "CSF phosphorylated tau",
     xlab   = "p-tau (pg/mL)")

# 
# There is the skew from the table above.
# 
# ---- One variable per group: a boxplot -----------------------------------------
# 
boxplot(moca ~ group, data = memclinic,
        xlab = "Diagnosis",
        ylab = "MoCA score")

# 
# The groups come out in clinical order **because we fixed the factor levels
# earlier**. Had we not, this plot would read AD, HC, MCI.
# 
# ---- Two variables: a scatterplot ----------------------------------------------
# 
plot(memclinic$hippo_vol_mm3, memclinic$stroop_cost_ms,
     pch  = 16,
     col  = "grey40",
     xlab = "Hippocampal volume (mm³)",
     ylab = "Stroop interference cost (ms)")

abline(lm(stroop_cost_ms ~ hippo_vol_mm3, data = memclinic), col = "blue")

# 
# That `abline(lm(...))` line has already fitted a regression — the kind of model
# the Regression 1 lecture is about.
# 
# `xlab` and `ylab` are not decoration. No plot should leave this room with
# `memclinic$moca` written along an axis.
# 
# ---- Several plots at once -----------------------------------------------------
# 
# `par(mfrow = c(rows, columns))` splits the plotting area into a grid.
# 
par(mfrow = c(2, 2))
hist(memclinic$age,  main = "Age",  xlab = "years")
hist(memclinic$moca, main = "MoCA", xlab = "score")
boxplot(hippo_vol_mm3 ~ group, data = memclinic, ylab = "Hippocampal volume")
plot(memclinic$age, memclinic$hippo_vol_mm3,
     xlab = "Age", ylab = "Hippocampal volume")
par(mfrow = c(1, 1))     # always put it back

# 
# Practical 5 opens with `par(mfrow = c(2, 2)); plot(m1)` to get four diagnostic
# plots in one figure. This is why.
# 
# ---- Wide and long -------------------------------------------------------------
# 
# Our second file has one row per person and three reaction-time columns:
# 
stroop <- read.csv("data/stroop-rm.csv")
head(stroop, 3)
nrow(stroop)

# 
# That is **wide** format. Most modelling functions want **long** format: one row
# per *observation*, with a column saying which condition it came from. You could
# build it by hand with what you already know:
# 
long_manual <- rbind(
  data.frame(id = stroop$id, condition = "congruent",   rt = stroop$rt_congruent),
  data.frame(id = stroop$id, condition = "neutral",     rt = stroop$rt_neutral),
  data.frame(id = stroop$id, condition = "incongruent", rt = stroop$rt_incongruent)
)
nrow(long_manual)
head(long_manual, 3)

# 
# 36 people × 3 conditions = 108 rows. `reshape()` does it in one call:
# 
long <- reshape(stroop,
                direction = "long",
                varying   = c("rt_congruent", "rt_neutral", "rt_incongruent"),
                v.names   = "rt",
                timevar   = "condition",
                times     = c("congruent", "neutral", "incongruent"),
                idvar     = "id")
rownames(long) <- NULL
head(long, 3)
nrow(long)

# 
# `reshape()` is the least friendly function in base R. Nobody memorises its
# arguments — copy this call and change the names. (`tidyr::pivot_longer()` is the
# modern alternative; the appendix shows it.)
# 
# ---- Joining the two files -----------------------------------------------------
# 
# `stroop-rm.csv` has no `group` column, on purpose. `merge()` attaches it from
# the cohort file, matching on `id`:
# 
long <- merge(long, memclinic[, c("id", "group", "age")], by = "id")
head(long, 3)

tapply(long$rt, long$condition, mean)

# 
# Reaction time rises from congruent to neutral to incongruent — the Stroop
# effect.
# 
# ---- The other way to draw this ------------------------------------------------
# 
# Every regression script in this course uses **ggplot2**, so it is worth seeing
# the same picture in both dialects. The professor's own comment in `Regression1.R`
# is *"better graphic facilities with ggplot package"*.
# 
library(ggplot2)      # notice the masking message

ggplot(memclinic, aes(x = hippo_vol_mm3, y = stroop_cost_ms)) +
  geom_point(alpha = .6) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Hippocampal volume (mm³)",
       y = "Stroop interference cost (ms)")

# 
# Three ideas and that is enough for now: `aes()` says which variable maps to
# which part of the picture, each `geom_` adds a layer, and layers are joined with
# `+`. You do not need it here, but every regression script in the course uses it,
# so it is worth having seen once.
# 
# ---- Exercises -----------------------------------------------------------------
# 
# ---- Exercise 1 — find the extreme cases ---------------------------------------
# 
# Pull out the most impaired patients, then look at the extremes of hippocampal
# volume across the whole cohort.
# 
severe <- subset(memclinic, group == "___" & moca < ___)
nrow(severe)

severe[order(severe$___), c("id", "moca", "hippo_vol_mm3")]

biggest <- memclinic[order(-memclinic$hippo_vol_mm3), ]
head(biggest[, c("id", "group", "hippo_vol_mm3")], 5)

# 
# 
# ---- Exercise 2 — a clinical flag, and the reference level ---------------------
# 
# Create a screening flag, then put the factor levels in clinical order and look
# at what happens to the model.
# 
memclinic$flag <- ifelse(memclinic$moca < 26, "___", "___")
table(memclinic$flag, memclinic$group)

memclinic$group <- factor(memclinic$group,
                          levels = c("___", "___", "___"))
levels(memclinic$group)

coef(lm(moca ~ group, data = memclinic))

# 
# 
# ---- Exercise 3 — summarise by group -------------------------------------------
# 
tapply(memclinic$hippo_vol_mm3, memclinic$___, mean)

aggregate(cbind(hippo_vol_mm3, csf_ptau) ~ ___, data = memclinic, FUN = ___)

psych::describe(memclinic[, c("___", "___")])

# 
# 
# ---- Exercise 4 — three plots --------------------------------------------------
# 
# Draw a histogram, a boxplot and a scatterplot, each with readable axis labels.
# 
hist(memclinic$___,
     breaks = 20,
     main   = "___",
     xlab   = "___")

boxplot(___ ~ ___, data = memclinic,
        xlab = "Diagnosis",
        ylab = "___")

plot(memclinic$age, memclinic$hippo_vol_mm3,
     pch  = 16,
     col  = "grey40",
     xlab = "___",
     ylab = "___")
abline(lm(___ ~ ___, data = memclinic), col = "blue")

# 
# 
# ---- Exercise 5 — wide to long -------------------------------------------------
# 
stroop <- read.csv("data/___.csv")
nrow(stroop)

long <- reshape(stroop,
                direction = "long",
                varying   = c("rt_congruent", "rt_neutral", "rt_incongruent"),
                v.names   = "rt",
                timevar   = "condition",
                times     = c("congruent", "neutral", "incongruent"),
                idvar     = "id")
rownames(long) <- NULL
nrow(long)

long <- merge(long, memclinic[, c("id", "group")], by = "___")
tapply(long$rt, long$condition, ___)

# 
# 
# ---- What to take away ---------------------------------------------------------
# 
# - In `df[rows, columns]`, the comma is what separates the two. One column with a
#   comma gives a vector, not a table.
# - `ifelse()` for two outcomes, `dplyr::case_when()` for more, first match wins.
# - A factor's levels are alphabetical unless you set them. The first level is the
#   baseline every model compares against.
# - `tapply()` and `aggregate()` summarise within groups.
# - Label your axes.
# - Wide is for reading, long is for modelling.
# 
# ---- Going further -------------------------------------------------------------
# 
# The [appendix for this session](appendix.qmd) covers loops and the apply family,
# pipes, graphics in more depth including saving figures to file, the other ways to
# reshape, and how `merge()` can silently duplicate your rows.
