# 3 · Appendix — doing things repeatedly
# Statistics for brain and cognitive sciences (CN2) -- 2026/27
# student script
#
# GENERATED FROM sessions/03-lists-dataframes-functions/appendix.qmd -- DO NOT EDIT THIS FILE.
# Edit the .qmd and re-render the website; this file is overwritten.
#
# Open the .Rproj in this folder first, so that "data/..." paths resolve.

# 
# Nothing here is examinable. It is here because the answer to "but where does
# that number actually come from?" is worth having written down.
# 
memclinic <- read.csv("data/memclinic.csv")
memclinic$group <- factor(memclinic$group, levels = c("HC", "MCI", "AD"))

# 
# ---- Lists are not vectorised --------------------------------------------------
# 
try({
xlis <- list(1, 2, 3)
xlis^2
})

# 
# Arithmetic works elementwise on a *vector*; a list is a generic container, so
# there is nothing to apply the operation to. The fix is to map a function over
# it:
# 
# purrr::map(xlis, function(x) x^2)

# 
lapply(xlis, function(x) x^2)

# 
# ---- The apply family ----------------------------------------------------------
# 
vars <- c("age", "moca", "hippo_vol_mm3")

sapply(memclinic[, vars], mean)     # simplifies to a vector
sapply(memclinic[, vars], range)    # ... or a matrix
str(lapply(memclinic[, vars], mean))   # lapply always returns a list

# 
# `sapply()` guesses at the output shape, which is convenient interactively and
# risky in a script. `vapply()` makes you state it, and then checks:
# 
vapply(memclinic[, vars], mean, numeric(1))

# 
names(Filter(is.numeric, memclinic))

pieces <- lapply(levels(memclinic$group), function(g) {
  d <- memclinic[memclinic$group == g, ]
  data.frame(group = g, n = nrow(d), mean_moca = round(mean(d$moca), 1))
})
do.call(rbind, pieces)

# 
# `do.call(rbind, ...)` stacks a list of data frames into one, and is the idiom
# you will see in simulation code.
# 
# ---- Preallocation, and why it matters -----------------------------------------
# 
groups <- levels(memclinic$group)

out <- numeric(length(groups))          # room reserved up front
for (i in seq_along(groups)) {
  out[i] <- mean(memclinic$moca[memclinic$group == groups[i]])
}
names(out) <- groups
round(out, 1)

# 
# Growing `out` with `c(out, value)` instead would make R copy the whole vector
# on every pass. For three groups it makes no difference; for a simulation with
# 10 000 iterations it is the difference between seconds and minutes.
# 
# ---- Anonymous functions and functions in lists --------------------------------
# 
sapply(memclinic[, c("age", "moca")], function(x) max(x) - min(x))

# R 4.1 shorthand
sapply(memclinic[, c("age", "moca")], \(x) max(x) - min(x))

# 
funs <- list(mean = mean, median = median, sd = sd)
sapply(funs, function(f) round(f(memclinic$moca), 2))

# 
# Functions are objects like anything else, so they can live in a list and be
# passed around.
# 
# ---- Composing functions, and pipes --------------------------------------------
# 
x <- c(4, 9, 16)

step1 <- log(x); exp(step1)       # step by step
exp(log(x))                       # nested, read inside out
x |> log() |> exp()               # native pipe, read left to right

# 
# The lecture teaches `%>%` from **magrittr**, which is what the tidyverse uses
# and what appears in `WinterBreakExercises.R`:
# 
# library(magrittr)
# x %>% log %>% exp

# 
# For straightforward use the two behave the same. `|>` is built into R and needs
# no package.
# 
# ---- Lexical scoping -----------------------------------------------------------
# 
z <- 10
f <- function() { z <- 99; z }

f()    # the local z
z      # the global one, untouched

# 
# **Name masking**: a name defined inside a function hides one outside it.
# **Dynamic lookup**: R looks inside the function first, then outward. In the
# lecture's phrasing — *what happens in the function stays in the function*,
# unless you super-assign with `<<-`, which you should almost never do.
# 
g <- function(a, b) a * 2
g(5)      # no error, even though b was never supplied

# 
# That is **lazy evaluation**: arguments are only evaluated if they are actually
# used. `b` was never touched, so its absence never came up.
# 
# ---- Nested lists --------------------------------------------------------------
# 
study <- list(
  site_PD = list(n = 120, lead = "Padova"),
  site_VR = list(n = 60,  lead = "Verona")
)

study$site_PD$n
study[["site_VR"]][["lead"]]

sapply(study, function(s) s$n)
sum(sapply(study, function(s) s$n))

# 
# A fitted model is exactly this shape, several levels deep, which is why
# `str()` on one produces so much output — and why `names()` is the friendlier
# way in.
# 
fit <- lm(stroop_cost_ms ~ hippo_vol_mm3, data = memclinic)
names(summary(fit))
summary(fit)$r.squared
summary(fit)$coefficients["hippo_vol_mm3", "Pr(>|t|)"]

# 
# Pulling a *p* value out by name like that is how you avoid retyping numbers
# into a report — and how you avoid the typo that follows.
