# 3 · Lists, data frames, control flow, functions
# Statistics for brain and cognitive sciences (CN2) -- 2026/27
# student script
#
# GENERATED FROM sessions/03-lists-dataframes-functions/index.qmd -- DO NOT EDIT THIS FILE.
# Edit the .qmd and re-render the website; this file is overwritten.
#
# Open the .Rproj in this folder first, so that "data/..." paths resolve.

# 
# ---- [⬇ Download this practical](../../handouts/03-lists-dataframes-functions.zip) ----
# 
# A zip containing the R script, the data, and an `.Rproj` file. Unzip it
# somewhere you can find again, then double-click the `.Rproj`.
# 
# Optional extra practice alongside **Introduction to R — Part 3**. It does not
# replace the lecture, and nothing here is assessed.
# 
# ---- What you will be able to do -----------------------------------------------
# 
# - build a list, and pick things out of it with `[`, `[[` and `$`;
# - explain why a data frame is a list, and what follows from that;
# - read the output of `str()` on a fitted model;
# - write `if`, `ifelse()` and `for`, and say when you do not need a loop;
# - write a function, with arguments and a return value.
# 
# ---- Before you start ----------------------------------------------------------
# 
# Double-click the `.Rproj` in this folder, then use **Ctrl+Enter**
# (**Cmd+Enter** on a Mac). Do **not** press *Source* while a `___` blank remains.
# 
# ---- Lists ---------------------------------------------------------------------
# 
# A list is a **generic vector**: a collection of components that can be objects
# of different types, and of different lengths.
# 
(lis1 <- list(1:5, c("a", "b"), c(TRUE, FALSE, TRUE), 2.3))

# 
str(lis1)
typeof(lis1)
is.list(lis1)

# 
# Components are usually named:
# 
patient <- list(id      = "P042",
                age     = 71,
                group   = "MCI",
                scores  = c(moca = 24, stroop = 118))
str(patient)

# 
# A list can contain a list, which makes it a **recursive** object — and is how
# every complicated thing in R is built.
# 
lis2 <- list(list(1, "a"), c(TRUE, FALSE))    # a list of 2
lis3 <- c(list(1, "a"), c(TRUE, FALSE))       # a list of 4

length(lis2); length(lis3)

# 
# `list()` nests. `c()` flattens one level. They look almost identical and do
# different things.
# 
# ---- Subsetting a list — `[`, `[[`, `$` ----------------------------------------
# 
# This is the single most confusing thing about lists, and it is worth ten
# minutes now to save an hour later.
# 
patient["age"]      # SINGLE bracket: a LIST containing age
patient[["age"]]    # DOUBLE bracket: the value itself
patient$age         # the same as [[ ]], for a named component

# 
class(patient["age"])
class(patient[["age"]])

# 
# `[` keeps the container, `[[` opens it. The usual image: a list is a train of
# carriages, `[` gives you a shorter train, `[[` gives you what is inside one
# carriage.
# 
patient[c("id", "group")]    # several components: still a list
patient[-1]                  # drop the first component
patient[["scores"]]["moca"]  # into a component, then inside it
patient$scores["moca"]       # the same

# 
# `unlist()` flattens the whole thing to a vector — note the coercion:
# 
unlist(patient)

# 
# ---- Data frames are lists -----------------------------------------------------
# 
# > Matrices are built on top of vectors with a `dim` attribute. Factors are built
# > on top of vectors with `class` and `levels`. Dataframes are built on top of
# > **lists**.
# 
# A data frame is a **named list of vectors, all of the same length**, with three
# attributes: `names`, `class`, and `row.names`.
# 
age   <- c(72, 68, 81, 74, 69)
sex   <- c("M", "F", "F", "M", "F")
group <- c("HC", "MCI", "AD", "HC", "MCI")

(df1 <- data.frame(age = age, sex = sex, group = group))

# 
str(df1)
attributes(df1)
typeof(df1)      # a list!
class(df1)       # ... labelled data.frame

# 
# Which means all the list subsetting you just learned applies:
# 
length(df1)      # the number of COLUMNS
df1[1]           # a data frame with one column
df1[[1]]         # the column itself, as a vector
df1$age          # the same

# 
# But a data frame also has the properties of a **matrix**, so `[row, column]`
# works too:
# 
dim(df1); nrow(df1); ncol(df1)
colnames(df1)
df1[2, ]          # second row
df1[, "age"]      # the age column
df1[2, "age"]     # one cell

# 
# That double nature — list and matrix at once — is what makes a data frame the
# right object for a dataset.
# 
is.factor(df1$sex)

# 
# Since **R 4.0.0** text columns stay as text. Older code and older textbooks
# assume the opposite. Convert explicitly when you need a factor.
# 
# ---- `summary()` behaves differently on factors --------------------------------
# 
summary(df1)

# 
# `sex` and `group` report `Length / Class / Mode`, which tells you nothing. Turn
# them into factors and the same call counts them:
# 
df1_F <- as.data.frame(unclass(df1), stringsAsFactors = TRUE)
summary(df1_F)

# 
# ---- Adding columns and combining frames ---------------------------------------
# 
df1$moca <- c(29, 24, 17, 28, 25)
df1$age_z <- with(df1, scale(age))    # with() saves repeating df1$
str(df1)

# 
extra <- data.frame(age = 77, sex = "F", group = "AD", moca = 19, age_z = NA)
rbind(df1, extra)                     # add rows

ids <- data.frame(row = 1:5, site = c("PD", "PD", "VR", "PD", "VR"))
head(cbind(df1, site = ids$site), 3)  # add columns

# 
# `merge()` joins two frames on a shared key, and is covered properly in
# practical 4.
# 
# ---- Tibbles -------------------------------------------------------------------
# 
# A tibble is a modern data frame from the tidyverse, which drops some of the
# older idiosyncrasies and prints more helpfully — it borrows the type
# information from `str()` and puts it in the printout.
# 
(tib0 <- tibble::tibble(x    = 1:3,
                        y    = 1,
                        z    = x^2 + y,
                        name = letters[1:3]))

# 
class(tib0)
tibble::is_tibble(tib0)

# 
# Note `y = 1` was recycled, and `z` could be defined using `x` and `y` in the
# same call — neither works in `data.frame()`. A tibble is still a data frame:
# `[`, `[[` and `$` all behave as you expect.
# 
# ---- Control flow --------------------------------------------------------------
# 
# ---- Choices -------------------------------------------------------------------
# 
score <- 24
if (score < 26) {
  print("below the screening cut-off")
} else {
  print("within normal limits")
}

# 
# `if()` takes **one** condition. For a whole vector, use the vectorised
# `ifelse()`:
# 
x <- 1:8
ifelse(x %% 2 == 0, "even", "odd")

# 
moca <- c(29, 24, 18, 27)
dplyr::case_when(
  moca >= 26 ~ "normal",
  moca >= 20 ~ "mild",
  TRUE       ~ "moderate-severe"
)

# 
# `case_when()` replaces nested `ifelse()`. **The conditions are evaluated in the
# order you write them**, and the first match wins, so `>= 26` must come before
# `>= 20`. The final `TRUE` is the catch-all.
# 
# ---- Loops ---------------------------------------------------------------------
# 
for (i in 1:4) print(i)

# 
for (g in c("HC", "MCI", "AD")) {
  cat(g, "\n")
}

# 
# `next` skips to the next iteration, `break` leaves the loop:
# 
for (i in 1:10) {
  if (i < 2) next
  if (i > 6) break
  cat(i, "")
}

# 
x <- 0
while (x < 4) { x <- x + 1 }
x

x <- 0
repeat { x <- x + 1; if (x == 4) break }
x

# 
# `while` tests the condition before each pass, `repeat` runs until you break out.
# There is no do-while statement in R.
# 
# 1. **Preallocate** — growing a vector each pass makes R copy it each time.
# 2. Loops can **strip attributes** from vectors.
# 3. **Vectorise** rather than nesting loops.
# 4. `1:length(x)` fails on an empty vector. Use `seq_along(x)`:
# 
x <- numeric(0)
1:length(x)      # counts DOWN from 1 to 0 -- two iterations on nothing
seq_along(x)     # empty, as it should be

# 
# ---- Functions -----------------------------------------------------------------
# 
# In data analysis, functions are how you call statistical methods — and they
# **typically return a list** holding both results and details.
# 
ttestex <- t.test(1:100, mu = 70)
class(ttestex)
names(ttestex)

# 
ttestex$p.value
ttestex$conf.int

# 
# Everything printed in a test result is a component you can pull out by name —
# which is how you put a number into a report without retyping it.
# 
# The same is true of a fitted model:
# 
memclinic <- read.csv("data/memclinic.csv")
fit <- lm(stroop_cost_ms ~ hippo_vol_mm3, data = memclinic)

class(fit)
names(fit)[1:6]
fit$coefficients

# 
# `class()` is `"lm"`, and that label is the whole reason `summary(fit)` prints a
# regression table rather than dumping a list. What that table means is the
# subject of the Regression 1 lecture.
# 
# ---- Writing your own ----------------------------------------------------------
# 
hypo <- function(a, b) {
  c = sqrt(a^2 + b^2)
  return(c)
}

hypo(3, 4)
hypo(a = 3, b = 4)

# 
# Notice the assignment discipline: `<-` binds the function to the name, `=`
# names arguments at the call site.
# 
# A function has three parts:
# 
formals(hypo)      # its arguments
body(hypo)         # what it does

# 
# Arguments can have defaults, and the last expression is returned even without
# `return()`:
# 
z_score <- function(x, na.rm = TRUE) {
  (x - mean(x, na.rm = na.rm)) / sd(x, na.rm = na.rm)
}

round(z_score(c(24, 26, 28, 30, 22)), 2)

# 
# Be careful with arguments and their position.
# 
sum(2, 3, 10)
mean(2, 3, 10)
args(mean)

# 
# `sum()` adds everything it is given. `mean()` takes **one** vector as its first
# argument, so `mean(2, 3, 10)` returns the mean of `2` — and silently ignores
# the rest. What you meant was `mean(c(2, 3, 10))`.
# 
f <- function() { hidden <- 99; hidden }
f()
exists("hidden")

# 
# What happens in the function stays in the function.
# 
# ---- Exercises -----------------------------------------------------------------
# 
# ---- Exercise 1 — a list, and the three brackets -------------------------------
# 
session <- list(
  id        = "P042",
  visit     = ___,
  scores    = c(moca = 24, stroop = 118, rt = 455),
  complete  = TRUE
)

str(session)

session["scores"]        # what class is this?
session[["scores"]]      # and this?
class(session[___])
class(session[[___]])

session$scores["moca"]   # reach inside the component

# 
# 
# ---- Exercise 2 — a data frame is a list ---------------------------------------
# 
memclinic <- read.csv("data/memclinic.csv")

typeof(memclinic)      # what is it made of?
class(memclinic)       # what is it labelled as?
length(memclinic)      # rows or columns?
nrow(memclinic)

# The same column, three ways
head(memclinic[["moca"]], 3)
head(memclinic$___, 3)
head(memclinic[, "___"], 3)

# And the container version
class(memclinic["moca"])
class(memclinic[["moca"]])

# 
# 
# ---- Exercise 3 — recoding with control flow -----------------------------------
# 
# A binary flag with the vectorised if
memclinic$flag <- ifelse(memclinic$moca < ___, "positive", "negative")
table(memclinic$flag)

# Three categories, first match wins
memclinic$severity <- dplyr::case_when(
  memclinic$moca >= 26 ~ "___",
  memclinic$moca >= 20 ~ "___",
  TRUE                 ~ "moderate-severe"
)
table(memclinic$severity)

# Why would putting the >= 20 line first be wrong?

# 
# 
# ---- Exercise 4 — write a function ---------------------------------------------
# 
# Write a function that takes a vector of scores and returns how many fall below
# a cut-off, with the cut-off as an argument that defaults to 26.
# 
n_below <- function(x, cutoff = ___) {
  sum(x < cutoff, na.rm = TRUE)
}

n_below(memclinic$moca)
n_below(memclinic$moca, cutoff = ___)

formals(n_below)

# Now break it on purpose: what does this give, and why?
mean(24, 26, 28)
mean(c(24, 26, 28))

# 
# 
# ---- What to take away ---------------------------------------------------------
# 
# - `[` keeps the container, `[[` and `$` open it.
# - A data frame **is** a list of equal-length columns, wearing a class label.
#   `length()` counts columns; use `nrow()` for rows.
# - `if` takes one condition; `ifelse()` and `case_when()` take a whole vector.
# - `case_when()` stops at the first match, so order the conditions from specific
#   to general.
# - A statistical function returns a list — everything in a printed result can be
#   pulled out by name.
# - Check the argument order of a function before you trust its answer.
# 
# ---- Going further -------------------------------------------------------------
# 
# The [appendix](appendix.qmd) covers nested lists and `purrr::map()`, the apply
# family, `seq_along()` and loop pitfalls in depth, anonymous functions, pipes,
# and lexical scoping.
