# 2 · Appendix — the rest of the type system
# Statistics for brain and cognitive sciences (CN2) -- 2026/27
# student script
#
# GENERATED FROM sessions/02-r-objects/appendix.qmd -- DO NOT EDIT THIS FILE.
# Edit the .qmd and re-render the website; this file is overwritten.
#
# Open the .Rproj in this folder first, so that "data/..." paths resolve.

# 
# Nothing here is examinable. It is here because the answer to "but where does
# that number actually come from?" is worth having written down.
# 
# ---- The atomic types you will probably never need -----------------------------
# 
# Beyond double, integer, character and logical, R has two more:
# 
z <- 8 + 9i
typeof(z); Re(z); Im(z); Mod(z)

r <- as.raw(c(1, 15, 255))
r; typeof(r)

# 
# `complex` turns up in signal processing — an FFT of an EEG trace returns
# complex numbers. `raw` is bytes, and you will meet it only if you read a binary
# file.
# 
# ---- Integers and doubles are stored differently -------------------------------
# 
typeof(1); typeof(1L)
object.size(1:1000000)
object.size(as.numeric(1:1000000))

# 
# The `L` suffix stores a whole number as an integer, at half the memory. It also
# accepts the other formats — `1234L`, `1e4L`, `0xcafeL`.
# 
# Doubles can be written several ways, all the same value:
# 
c(0.1234, 1.234e-1, 1234e-4)
0xcafe          # hexadecimal

# 
# And three special doubles:
# 
c(Inf, -Inf, NaN)
1/0; -1/0; 0/0

# 
# ---- `typeof()` is really `storage.mode()` -------------------------------------
# 
typeof(mtcars)
storage.mode(mtcars)

# 
# Both say `list`, because that is how a data frame is *stored*. The `class`
# attribute is what makes it behave like a table. To see the actual C-level
# object:
# 
# lobstr::sxp(mtcars)    # VECSXP -- the internal name for a generic vector

# 
# ---- `structure()` and homemade attributes -------------------------------------
# 
# Attributes are not only for R's own use. You can annotate your own data:
# 
rt <- structure(c(412, 455, 398),
                units    = "ms",
                task     = "Stroop, incongruent",
                measured = as.Date("2026-03-14"))

str(rt)
attr(rt, "task")
mean(rt)        # the attributes do not get in the way

# 
# This is a lightweight way to keep a note of where numbers came from, inside the
# object itself. But remember that most operations discard it:
# 
attributes(rt * 2)

# 
# Only `names` and `dim` survive.
# 
# ---- Why `solve()` is the same thing as fitting a regression -------------------
# 
# Practical 2 used `solve(A, b)` to solve two equations in two unknowns. A
# regression is the same operation with more rows than unknowns.
# 
memclinic <- read.csv("data/memclinic.csv")

y <- memclinic$stroop_cost_ms
X <- cbind(intercept = 1, hippo = memclinic$hippo_vol_mm3)

head(X, 3)

# the normal equations: (X'X)^-1 X'y
solve(t(X) %*% X) %*% t(X) %*% y

# 
coef(lm(stroop_cost_ms ~ hippo_vol_mm3, data = memclinic))

# 
# Identical. `lm()` is a well-tested, numerically careful implementation of that
# one line, and everything else it gives you — standard errors, *t* values,
# diagnostics — is built on top of it.
# 
# This also explains why perfectly correlated predictors break a regression:
# `t(X) %*% X` becomes non-invertible, and `solve()` has nothing to return.
# 
try({
Xbad <- cbind(1, 1:5, 2 * (1:5))    # third column is twice the second
solve(t(Xbad) %*% Xbad)
})

# 
# ---- Arrays, and when you would use one ----------------------------------------
# 
arr <- array(1:24, dim = c(2, 3, 4))
dim(arr)
arr[, , 2]

# 
# The natural use in this field is a 3-D image volume, or a
# participants × conditions × timepoints design:
# 
set.seed(1)
rt <- array(round(rnorm(2 * 3 * 4, 450, 40)),
            dim = c(2, 3, 4),
            dimnames = list(participant = c("P01", "P02"),
                            condition   = c("congruent", "neutral", "incongruent"),
                            block       = paste0("b", 1:4)))
rt["P01", , "b1"]
apply(rt, c("condition"), mean)    # average over everything but condition

# 
# In practice you would hold this as a long data frame instead, which is what
# practical 4 builds — but `apply()` over an array margin is sometimes the
# clearest way to say what you mean.
# 
# ---- `identical()`, `all.equal()`, and `==` ------------------------------------
# 
a <- c(1, 2, 3)
b <- c(1, 2, 3)

a == b                      # elementwise, a vector
identical(a, b)             # one answer: exactly the same object?
identical(1L, 1)            # FALSE -- integer is not double
isTRUE(all.equal(1L, 1))    # TRUE -- equal to within tolerance

# 
# Use `==` for data, `identical()` for exact structural equality, and
# `isTRUE(all.equal())` inside an `if()` when comparing computed decimals.
