# 2 · R objects, attributes, matrices
# Statistics for brain and cognitive sciences (CN2) -- 2026/27
# student script
#
# GENERATED FROM sessions/02-r-objects/index.qmd -- DO NOT EDIT THIS FILE.
# Edit the .qmd and re-render the website; this file is overwritten.
#
# Open the .Rproj in this folder first, so that "data/..." paths resolve.

# 
# ---- [⬇ Download this practical](../../handouts/02-r-objects.zip) --------------
# 
# A zip containing the R script, the data, and an `.Rproj` file. Unzip it
# somewhere you can find again, then double-click the `.Rproj`.
# 
# Optional extra practice alongside **Introduction to R — Part 2**. It does not
# replace the lecture, and nothing here is assessed.
# 
# ---- What you will be able to do -----------------------------------------------
# 
# - name the atomic types, and predict what happens when you mix them;
# - build a vector, subset it every way there is, and **replace** parts of it;
# - explain why `c(1, 2, 3, 4) + c(10, 20)` gives an answer rather than an error;
# - use `which()`, `any()`, `all()` and `%in%`;
# - tell `NA` from `NaN` from `Inf`;
# - see that a matrix and a factor are just vectors with **attributes** attached;
# - build a factor with the levels in the order you want;
# - do matrix arithmetic, including the difference between `*` and `%*%`.
# 
# ---- Before you start ----------------------------------------------------------
# 
# Double-click the `.Rproj` file in this folder. Then use **Ctrl+Enter**
# (**Cmd+Enter** on a Mac) line by line — do **not** press *Source*, which will
# fail on the whole file while any `___` blank is unfilled.
# 
# ---- Two kinds of object -------------------------------------------------------
# 
is.object(1:10)      # a vector is a base object
is.object(mtcars)    # a data.frame is an S3 object

# 
# Base objects have a **base type** and are what everything else is built from.
# S3 objects additionally carry a `class`, which tells R to treat them specially.
# The `sloop` package names the system:
# 
# sloop::otype(1:10)     # "base"
# sloop::otype(mtcars)   # "S3"

# 
# ---- Atomic types --------------------------------------------------------------
# 
# R stores data as one of a few atomic types:
# 
# - **numeric**, which is either `double` (any real number) or `integer`;
# - **character**, for strings;
# - **logical**, `TRUE` or `FALSE` (or `T` / `F`).
# 
typeof(5)
typeof("cat")
typeof(TRUE)
typeof(5L)     # the L suffix forces an integer

# 
# `class()` reports what R's statistical machinery treats an object as; objects
# with no explicit class still carry an implicit one.
# 
class(1:10)      # implicit class
class(mtcars)    # a real S3 class
typeof(mtcars)   # what it is stored as underneath

# 
# A data frame is stored as a **list**. That is not a curiosity — it is the point
# of practical 3.
# 
# ---- Logicals behave like numbers ----------------------------------------------
# 
5 < 13
as.numeric(TRUE); as.numeric(FALSE)
TRUE + TRUE + FALSE

# 
# The Boolean operators are `<`, `<=`, `==`, `>=`, `>`, `!=`, `!`, `&`, `&&`,
# `|`, `||`.
# 
c(TRUE, TRUE) & c(TRUE, FALSE)    # elementwise: one answer per element
TRUE && FALSE                     # a single comparison

# 
# `&` and `|` work on **every element** of a vector. `&&` and `||` take a single
# `TRUE` or `FALSE` on each side and belong inside `if()`.
# 
# 
# Note also that `==` and `identical()` ask different questions:
# 
c(1, 2) == c(1, 2)
identical(c(1, 2), c(1, 2))

# 
# ---- Testing and coercing ------------------------------------------------------
# 
is.character(100.5)
is.logical(TRUE)
as.character(100.5)
as.integer("42")

# 
# Every type has an `is.something()` and an `as.something()`.
# 
# `is.vector()`, `is.atomic()` and `is.numeric()` do not mean quite what you would
# guess — check their help pages before relying on them.
# 
# ---- Vectors -------------------------------------------------------------------
# 
# The vector is the most important object in R: a collection of adjacent values
# of **one** type.
# 
vec1 <- c(1, 5, 9.6, 4)
vec2 <- c("a", "b", "9.5")
vec3 <- c(TRUE, FALSE, FALSE)

typeof(vec1); typeof(vec2); typeof(vec3)

# 
# ---- One type only, and R will not ask -----------------------------------------
# 
# If you mix types, everything is coerced up the hierarchy:
# 
# > **Character > Double > Integer > Logical**
# 
vec4 <- c(1, 5, 9.6, 4, "a")
typeof(vec4)
vec4

# 
# The quotes give it away: every number became text.
# 
# No error, no warning. If a column of numbers ever refuses to behave
# arithmetically, this is the first thing to check.
# 
# Two quick checks from the lecture — predict, then run:
# 
typeof(c(TRUE, FALSE, FALSE, "a"))
typeof(c(1, 5, 9.6, 4, TRUE))
typeof(c(1, 3, 4)); typeof(c(1L, 3L, 4L))

# 
# ---- Naming elements -----------------------------------------------------------
# 
(vec <- c(Frodo = 32, Bilbo = 64, Gandalf = 101))
length(vec)
names(vec)

# 
vec <- setNames(c(32, 64, 101), c("Frodo", "Bilbo", "Gandalf"))
vec

# 
# R also ships the alphabet:
# 
letters[1:5]
LETTERS[1:5]

# 
# ---- Subsetting a vector -------------------------------------------------------
# 
vec <- c(1, 3, 5, 7, 9, 12)
vec[1]                 # first element
vec[-3]                # everything except the third
vec[length(vec)]       # last element
vec[c(1, 3)]           # first and third
vec[-c(1, 3)]          # all but first and third
vec[vec > 3]           # everything greater than 3

# 
# By name:
# 
names(vec) <- LETTERS[1:length(vec)]
vec
vec["A"]

# 
# ---- Replacing by subsetting ---------------------------------------------------
# 
# Anything you can select, you can assign to:
# 
vec[3] <- 8                      # replace the third
vec[c(1, 2)] <- c(44, 88)        # replace two
vec["C"] <- 4                    # replace by name
vec[vec > 40] <- NA              # replace everything over 40
vec

# 
# The last line is how you censor implausible values in real data — a reaction
# time of 20 000 ms, say — in one line.
# 
# ---- Patterned vectors ---------------------------------------------------------
# 
seq(from = 3, to = 10, by = 1)
3:10                             # the colon is a shortcut
seq(from = 0, to = 1, length.out = 5)

# 
rep(2, 5)
rep(c(1, 2), 2)
rep(c(1, 2, 3), each = 2)
rep(c(1, 2, 3), each = 2, times = 2)
rep(1:3, 1:3)                    # each element repeated its own number of times

# 
# `rep(..., each = )` is exactly how the diagnostic groups in `memclinic.csv`
# were built.
# 
# ---- Recycling -----------------------------------------------------------------
# 
vec <- c(1, 5, 3, 7, 9)
vec > 4        # how can R compare a length-5 vector to a length-1 one?
vec + 100

# 
# R **recycles** the shorter vector until it matches the longer one. That is what
# makes `vec + 100` work. But it also does this:
# 
1:3 + 1:9

# 
c(1, 2, 3) + c(10, 20)

# 
# R only warns when the longer length is **not a multiple** of the shorter one.
# When it is a multiple, you get a wrong answer of the right length and no
# warning at all.
# 
# ---- `which()`, `any()`, `all()`, `%in%` ---------------------------------------
# 
vec <- c(1, 10, 50, 100)
which(vec > 3 & vec < 90)     # the POSITIONS of the matches
any(vec > 3)                  # is at least one TRUE?
all(vec <= 100)               # are they all TRUE?

# 
# Note the difference: `vec[vec > 3]` gives you the *values*, `which(vec > 3)`
# gives you *where they are*.
# 
grp <- c("HC", "MCI", "AD", "HC")
"AD" %in% grp
grp %in% c("MCI", "AD")

# 
# `x %in% y` is shorthand for "is `x` anywhere in `y`", and works elementwise.
# 
# ---- Element-by-element arithmetic ---------------------------------------------
# 
x <- 1:3; y <- 3:1
x + y
x * y
x^y
x %/% y     # integer division
x %% y      # remainder

# 
# A use for the remainder — picking out even numbers:
# 
v <- 21:40
v[v %% 2 == 0]
which(v %% 2 == 0)

# 
# ---- Inner and outer product ---------------------------------------------------
# 
# Because `*` is elementwise, the matrix products have their own operators:
# 
a <- 1:3; b <- 4:6
a %*% b        # inner (scalar, dot) product
outer(a, b)    # outer product

# 
# ---- Missing values ------------------------------------------------------------
# 
is.na(c(1, 3, NA, 4))
mean(c(1, 3, NA, 4))
mean(c(1, 3, NA, 4), na.rm = TRUE)

# 
# Any operation involving `NA` returns `NA` — the value is unknown, so anything
# computed from it is unknown too.
# 
# Three different special values, easily confused:
# 
typeof(NA)          # logical: Not Available
typeof(NaN)         # double:  Not a Number, e.g. 0/0
0 / 0
1 / 0

is.na(c(NA, NaN, Inf))     # TRUE for NA and NaN -- both are "missing"
is.nan(c(NA, NaN, Inf))    # TRUE only for NaN
is.finite(c(NA, NaN, Inf))

# 
v <- c(1, NA, 3)
v[v > 2]

# 
# Only one value is above 2, but two things came back. `NA > 2` is `NA`, and
# indexing with `NA` returns a missing value.
# 
# ---- Attributes ----------------------------------------------------------------
# 
# Vectors become other objects by having **attributes** attached — metadata
# carried along with the values.
# 
x <- 1:10
attr(x, "units") <- "milliseconds"
attr(x, "measured_by") <- "E-Prime"
attributes(x)

# 
# `structure()` sets them all at once:
# 
x <- structure(1:10, units = "milliseconds", measured_by = "E-Prime")
str(x)

# 
# Most attributes are lost by most operations:
# 
attributes(x[1])

# 
# `NULL` means an empty vector — here, no attributes at all. **Two** attributes
# are always preserved: `names` and `dim`.
# 
# ---- `dim` turns a vector into a matrix ----------------------------------------
# 
mat1 <- matrix(1:8, nrow = 2, ncol = 4)

mat2 <- 1:8
dim(mat2) <- c(2, 4)     # just adding an attribute

identical(mat1, mat2)

# 
# A matrix is not a new kind of thing. It is a vector with a `dim` attribute.
# 
# ---- `class` turns a vector into a factor --------------------------------------
# 
summary(c(1, 2, 1, 2, 1, 1, 1, 2))
summary(factor(c(1, 2, 1, 2, 1, 1, 1, 2)))

# 
# Same eight numbers. Assigning a class tells R to use a different version of
# `summary()` — a mean for numbers, counts for categories.
# 
# ---- Factors -------------------------------------------------------------------
# 
vecf <- c("A1", "A2", "A3", "A1", "A2")
(fac1 <- factor(vecf))
levels(fac1)

# 
# Underneath, a factor is an **integer** vector with two attributes:
# 
typeof(fac1)
class(fac1)
attributes(fac1)

# 
# Because the storage is integer codes, converting a factor to a number gives you
# the codes, not the values:
# 
dose <- factor(c(10, 20, 30))
as.numeric(dose)                    # 1 2 3 -- the codes
as.numeric(as.character(dose))      # 10 20 30 -- the fix

# 
# ---- `table()`, and empty levels -----------------------------------------------
# 
sex_char   <- c("m", "m", "m")
sex_factor <- factor(sex_char, levels = c("m", "f"))

table(sex_char)
table(sex_factor)

# 
# The factor version reports `f: 0`. A character vector cannot know that "f" was
# a possible answer; a factor can, because you told it. This matters whenever a
# group happens to have no observations — a factor keeps the empty cell, text
# silently drops it.
# 
# ---- Ordered factors -----------------------------------------------------------
# 
severity <- factor(c("mild", "severe", "moderate"),
                   levels  = c("mild", "moderate", "severe"),
                   ordered = TRUE)
severity
class(severity)
severity[1] < severity[2]

# 
# An ordered factor knows its levels have a direction, so comparisons work.
# 
# ---- Matrices ------------------------------------------------------------------
# 
mat <- matrix(c(1, 2), nrow = 2, ncol = 2)   # c(1,2) is recycled
colnames(mat) <- letters[1:2]
rownames(mat) <- LETTERS[1:2]
mat

# 
# Like vectors, a matrix holds **one** type:
# 
typeof(matrix(c(1, 2, 3, TRUE, FALSE, FALSE), 3, 2))
typeof(matrix(c("a", "b", "c", 1, 2, 3), 3, 2))

# 
# ---- Subsetting ----------------------------------------------------------------
# 
mat <- matrix(1:6, nrow = 2, ncol = 3)
mat
dim(mat); nrow(mat); ncol(mat)

mat[1, 3]      # row 1, column 3
mat[2, ]       # all of row 2
mat[, 2]       # all of column 2
mat[, -2]      # drop column 2
mat[1:2, 1:2]  # a block

# 
# Every subsetting method you learned for vectors works here too.
# 
# ---- Binding, diagonal, transpose ----------------------------------------------
# 
A <- matrix(1:6, 2, 3)
B <- matrix(6:1, 2, 3)

cbind(A, B)
rbind(A, B)

# 
M <- matrix(c(1, 2), 2, 2)
diag(M)          # the diagonal of a matrix
diag(c(1, 2))    # ... or build a diagonal matrix
t(A)             # transpose

# 
# ---- Arithmetic, and the two products ------------------------------------------
# 
matrix(1:6, 2, 3) + matrix(6:1, 2, 3)
matrix(1:6, 2, 3) - matrix(6:1, 2, 3)

# 
matrix(1/(1:6), 2, 3) * matrix(1:6, 2, 3)        # elementwise
matrix(1/(1:6), 2, 3) %*% matrix(1:6, 3, 2)      # matrix product

# 
# `*` multiplies position by position and needs identical shapes. `%*%` is the
# matrix product and needs the inner dimensions to agree.
# 
# ---- Determinant, inverse, and solving systems ---------------------------------
# 
M <- matrix(1:4, 2)
det(M)
solve(M)              # the inverse
M %*% solve(M)        # ... which gives the identity

# 
# `solve()` with two arguments solves a linear system. The system
# 
# $$\begin{cases} y = x + 3 \\ y = -x + 3\end{cases}$$
# 
# becomes:
# 
A1 <- matrix(c(-1, 1, 1, 1), 2)
solve(A1, c(3, 3))

# 
# This is not an aside: fitting a regression is solving a system of exactly this
# kind — which is what `lm()` does once the course reaches Regression 1.
# 
# ---- Arrays --------------------------------------------------------------------
# 
arr <- array(1:24, dim = c(2, 3, 4))
dim(arr)
arr[1, 2, 3]     # one element
arr[, , 1]       # the first 2x3 slice

# 
# An array is a vector with a longer `dim`. Vectors, matrices and arrays are all
# base objects — the same thing wearing different attributes.
# 
vec1 <- c(25, 24, 21, 23, 22, 31, 45, 90)
mat1 <- matrix(vec1, 2, 4)
arr1 <- array(vec1, c(2, 2, 2))

is.object(vec1)
class(vec1); class(mat1); class(arr1)
typeof(vec1); typeof(mat1); typeof(arr1)

# 
# ---- Exercises -----------------------------------------------------------------
# 
# ---- Exercise 1 — types and coercion -------------------------------------------
# 
moca <- c(29, 24, 18, 27, ___, ___)
typeof(moca)

# Add one piece of text and look at what happens to the rest
mixed <- c(moca, "missing")
typeof(___)
mixed

# Logicals are numbers: how many are below the cut-off, and what proportion?
sum(moca < ___)
mean(moca < ___)

# 
# 
# ---- Exercise 2 — subsetting and replacing -------------------------------------
# 
rt <- c(412, 455, 398, 9999, 467, 421)
names(rt) <- c("P01", "P02", "P03", "P04", "P05", "P06")

rt["P03"]              # by name
rt[-4]                 # everything except the fourth
rt[rt > 500]           # the implausible one
which(rt > ___)        # WHERE it is

# 9999 is a recording error. Replace it with NA in one line.
rt[rt > 500] <- ___
rt
mean(rt, na.rm = ___)

# 
# 
# ---- Exercise 3 — recycling, and a silent wrong answer -------------------------
# 
rt <- c(412, 455, 398, 467, 421, 430)

# Subtract a baseline of 400 from every value
rt - ___

# Now subtract a vector of TWO baselines. Predict the length before you run it.
rt - c(400, ___)

# And one of length four
rt - c(400, 410, 420, 430)

# 
# 
# ---- Exercise 4 — factors with the levels in the right order -------------------
# 
memclinic <- read.csv("data/memclinic.csv")

# group came in as text. Make it a factor and look at the levels.
g_default <- factor(memclinic$group)
levels(___)

# Now set them in clinical order instead
g_clinical <- factor(memclinic$group,
                     levels = c("___", "___", "___"))
levels(g_clinical)

table(g_clinical)

# 
# 
# ---- Exercise 5 — the lecture's matrix exercises -------------------------------
# 
# These are Exercises 1, 2, 4 and 5 from the lecture slides.
# 
# (1) Build these and transpose them
#     A is 2x4, B is 4x3, c is a 1x5 row vector
A <- matrix(c(5, -5, 7, 67, 90, -96, 1, 12), nrow = ___, ncol = ___)
A
t(A)

# (2) With these A and B, compute B + A and B - A
A2 <- matrix(c(1, 2, 1, 2, -1, 3, 3, -2, 6), nrow = 3)
B2 <- matrix(c(4, 2, 2, 2, 3, 2, 1, 2, 0), nrow = 3)
B2 + ___
B2 - ___

# (4) With these, compute AB and BA. Why are they different sizes?
A3 <- matrix(c(1, 3, 2, 1, 1, 0), nrow = 3)
B3 <- matrix(c(1, 2, 2, 3, 3, 4), nrow = 2)
A3 %*% ___
B3 %*% ___

# (5) Determinant and inverse, and check that A A^-1 is the identity
A4 <- matrix(c(11, 3, 3, 2), nrow = 2)
det(___)
solve(___)
A4 %*% solve(A4)

# 
# 
# ---- What to take away ---------------------------------------------------------
# 
# - A vector holds one type. Mixing types coerces silently, upward:
#   Character > Double > Integer > Logical.
# - Anything you can select, you can assign to.
# - R recycles a short vector to match a long one, and only warns when the lengths
#   do not divide evenly.
# - `NA` is unknown, `NaN` is not a number, `Inf` is infinite. `is.na()` is `TRUE`
#   for the first two.
# - A matrix is a vector with a `dim`; a factor is an integer vector with `levels`
#   and a `class`. Attributes are what make them different.
# - `*` is elementwise, `%*%` is the matrix product.
# 
# ---- Going further -------------------------------------------------------------
# 
# The [appendix](appendix.qmd) covers the remaining atomic types, integer versus
# double storage, `structure()` in more depth, arrays, and why `solve()` is the
# same operation as fitting a regression.
