# 1 · Basics of R
# Statistics for brain and cognitive sciences (CN2) -- 2026/27
# student script
#
# GENERATED FROM sessions/01-r-basics/index.qmd -- DO NOT EDIT THIS FILE.
# Edit the .qmd and re-render the website; this file is overwritten.
#
# Open the .Rproj in this folder first, so that "data/..." paths resolve.

# 
# ---- [⬇ Download this practical](../../handouts/01-r-basics.zip) ---------------
# 
# A zip containing the R script, the data, and an `.Rproj` file. Unzip it
# somewhere you can find again, then double-click the `.Rproj`.
# 
# Optional extra practice alongside **Introduction to R — Part 1**. It does not
# replace the lecture, and nothing here is assessed.
# 
# ---- What you will be able to do -----------------------------------------------
# 
# - use R as a calculator, and recognise when floating-point arithmetic has
#   tricked you;
# - create objects, and say what `<-` does that `=` does not;
# - find your way around the help system;
# - see what is in your workspace, and clear it;
# - set up a working directory properly, and read a data file from it;
# - run `str()` on anything and read what it tells you.
# 
# ---- Before you start ----------------------------------------------------------
# 
# Double-click the `.Rproj` file in this folder before anything else. That sets
# R's working directory, which is why nothing here calls `setwd()`.
# 
# If you later see
# 
# ```
# cannot open file 'data/memclinic.csv': No such file or directory
# ```
# 
# run `getwd()` and `list.files()`. If there is no `data` folder in the list, you
# opened the script instead of the project. Close RStudio and double-click the
# `.Rproj` file.
# 
# Put your cursor on a line and press **Ctrl+Enter** (**Cmd+Enter** on a Mac).
# 
# Do **not** press the *Source* button. R reads the whole file before it runs any
# of it, and the `___` blanks in the exercises are not valid R until you fill them
# in. Pressing *Source* with a blank still in the file gives
# `Error: unexpected input` and runs **nothing at all**.
# 
# | Symbol | Mac | Windows |
# |---|---|---|
# | `<-` | Option + − (RStudio inserts it for you) | Alt + − |
# | `~` | Option + 5 | AltGr + ì |
# | `[` `]` | Option + è / Option + + | AltGr + è / AltGr + + |
# | `{` `}` | Shift + Option + è / Shift + Option + + | Shift + AltGr + è / + |
# | `#` | Option + à | AltGr + à |
# 
# Use the **copy button** in the corner of each grey box rather than selecting
# text — copying from a browser can turn `"` into `"`, which R will not accept.
# 
# ---- R as a giant pocket calculator --------------------------------------------
# 
3 * (2 + 4)
sqrt(144)
exp(1)
log(100)

# 
# The lecture's table of operators and functions — `+ - * / ^`, `sqrt`, `exp`,
# `log`, `sin`, `cos`, `min`, `max`, `range`, `length`, `sum`, `mean`, `var` —
# all work this way.
# 
# Two things that catch everyone in the first ten minutes:
# 
# - If the console shows **`+`** instead of **`>`**, R is waiting for you to
#   finish something, usually a missing bracket. Press **Esc**.
# - R is **case sensitive**: `Mean` is not `mean`.
# 
# ---- Finite precision ----------------------------------------------------------
# 
sqrt(2)^2 == 2
print(sqrt(2)^2, digits = 22)

# 
# Computers approximate real numbers, so two quantities that are equal on paper
# may differ in the last few digits. Never test exact equality of decimals:
# 
dplyr::near(sqrt(2)^2, 2)
1 / 49 * 49 == 1
dplyr::near(1 / 49 * 49, 1)

# 
# This is also the first time you see `pkg::fun()` — calling a function *without*
# loading its package. It makes clear where the function came from.
# 
# ---- Expressions and assignments -----------------------------------------------
# 
# An **expression** is evaluated, printed, and the value is lost. An
# **assignment** is evaluated, not printed, and the value is stored under a name.
# 
12 + 13        # an expression: shown, then gone
x <- 12 + 13   # an assignment: stored, nothing shown
x

# 
# Wrapping the whole assignment in round brackets stores *and* prints:
# 
(x <- 12 + 13)

# 
# You will see this throughout the course as `(model <- lm(...))`.
# 
# Other command syntax from the lecture:
# 
12 + 13; sqrt(9)      # ';' separates commands on one line
# a line starting with # is a comment and is not executed

# 
# ---- `<-` or `=`? --------------------------------------------------------------
# 
# Both assign, but they are **not interchangeable**. The rule from the lecture:
# 
# > Use `=` to assign values to an **argument in a function**, and `<-` to assign
# > values to a **variable**.
# 
# `ls()` lists what is in your workspace, which makes the difference visible:
# 
rm(list = ls())     # empty the workspace first
mean(x = 1:10)      # 'x' here names an argument of mean()
ls()                # nothing was created

# 
mean(x <- 1:10)     # this ALSO creates a variable called x
ls()

# 
# Same answer; the second version left an object behind.
# 
x < - 5
x

# 
# With a space in the middle, `<-` becomes `<` followed by `-`, so R read it as
# "is `x` less than minus five?", answered `FALSE`, and stored nothing. `x` is
# unchanged. No error, no warning.
# 
# There is also a function form:
# 
assign("y", 13 + 14)
y

# 
# ---- Naming things -------------------------------------------------------------
# 
# Names may be any length, are case sensitive, and may contain letters, digits,
# `.` and `_`. They must start with a letter (or a dot not followed by a digit).
# 
# The lecture's style advice:
# 
# - stick to ASCII, so your code travels;
# - start with letters, put numbers at the end;
# - use `_` to separate words — `snake_case` or `camelCase`;
# - you *can* use `.` as a separator, but better to avoid it;
# - **use names that make sense.**
# 
reaction_time <- 412      # good
rt2 <- 412                # fine

# 
# Do not name a variable after a function you use — `mean`, `c`, `data`, `df`,
# `T`, `F`. `T <- FALSE` is legal and will quietly break things later.
# 
# ---- Everything is an object ---------------------------------------------------
# 
# > "To understand computations in R, two slogans are helpful: Everything that
# > exists is an object. Everything that happens is a function call."
# > — John Chambers
# 
# A name does not *contain* a value; it is **bound** to one. `y <- 2 * sqrt(177) + 3`
# does not create an object called `y` — it binds the label `y` to a stored
# number.
# 
y1 <- y <- 2 * sqrt(177) + 3
y; y1

# 
# That is two names pointing at **one** object, not two objects.
# 
# ---- The help system -----------------------------------------------------------
# 
# ?mean                  # help for a function you can name
# help(mean)             # the same thing
# ??regression           # search for a topic
# apropos("mean")        # functions whose name contains "mean"
# example(seq)           # run the examples from the help page

# 
# Help pages have several sections. At this stage you need **Arguments** (what
# you can pass in) and **Examples** (at the bottom, ready to copy).
# 
# ---- Packages ------------------------------------------------------------------
# 
# install.packages("psych", dependencies = TRUE)   # once per computer
# library(psych)                                   # once per session
# installed.packages()                             # what is installed
# packageVersion("psych")
# detach(package:psych)                            # unload it

# 
# Do not use `remove.packages()` to unload a package — that **deletes** it.
# Use `detach()`.
# 
# Loading a package puts its functions on the search path:
# 
search()

# 
# Environments, in the lecture's phrase, are "bags of names". The Global
# Environment — your workspace — is the first one. When two packages define the
# same function name, the one loaded later **masks** the earlier one, and R tells
# you so. `pkg::fun()` sidesteps the question entirely.
# 
# ---- The workspace -------------------------------------------------------------
# 
a <- 10; b <- 1:10
ls()          # what is here
ls.str()      # ... and what each thing is

# 
rm(a)         # remove one object
ls()
rm(list = ls())   # remove EVERYTHING
ls()

# 
# `rm(list = ls())` opens almost every script in this course. Now you know it
# just deleted your work — and that you should not put it in a script you hand to
# someone else.
# 
# ---- Working directories -------------------------------------------------------
# 
# R always has one **current working directory**, and relative paths are
# interpreted from it.
# 
# getwd()          # where am I
# list.files()     # what is here
# list.files("data")

# 
# The lecture sets this with `setwd("C:/Somewhere/DirectoryName")`. Note that
# forward slashes work on every system, and a single backslash does not.
# 
# **In this course you will not need `setwd()` at all.** Every practical folder
# contains an `.Rproj` file; opening it sets the working directory to that folder.
# That is better than `setwd()` because the path is not written into the script,
# so the same script works on your computer and on mine.
# 
# ---- Reading data --------------------------------------------------------------
# 
memclinic <- read.csv("data/memclinic.csv")

# 
# The lecture lists the main readers:
# 
# | Function | For |
# |---|---|
# | `read.table(file, header = TRUE, sep = "\t")` | general text files |
# | `read.csv(file)` | comma-separated, decimal point |
# | `read.csv2(file)` | **semicolon**-separated, decimal **comma** — the common European export |
# | `readxl::read_excel(file)` | Excel |
# | `data(name, package = )` | a dataset that ships with a package |
# 
# We use `read.csv()` because these files are comma-separated with decimal
# points. If you ever open one in Excel on an Italian system and save it, you
# will need `read.csv2()` instead — which is a good reason not to open it in
# Excel.
# 
# ---- `str()` is your best friend -----------------------------------------------
# 
# The lecture says it twice, so it is worth repeating: **learn `str()`**. It
# tells you what any object actually is.
# 
str(memclinic)

# 
# 180 people assessed at a memory clinic — healthy controls, mild cognitive
# impairment, and early Alzheimer's disease — with MRI and cognitive measures.
# The [codebook](data/codebook.md) explains every column.
# 
head(memclinic, 3)
dim(memclinic)
summary(memclinic$moca)

# 
# What a data frame *is* made of is the subject of practical 3. For now it is a
# table you can look at.
# 
# ---- Exercises -----------------------------------------------------------------
# 
# Fill in each `___`, and run the lines one at a time with Ctrl+Enter.
# 
# ---- Exercise 1 — the calculator, and its limits -------------------------------
# 
# A reaction time of 412 ms, expressed in seconds
412 / ___

# Two ways of getting the same number
0.1 + 0.2
0.3

# Are they equal?
0.1 + 0.2 == ___
print(0.1 + 0.2, digits = 22)
dplyr::near(0.1 + 0.2, ___)

# 
# 
# ---- Exercise 2 — assignment, and what it leaves behind ------------------------
# 
rm(list = ls())

# Store a participant's age, then print it in one line
(age <- ___)

# Which of these creates a variable? Check with ls() after each.
mean(x = 1:20)
ls()

mean(x <- 1:20)
___()

# 
# 
# ---- Exercise 3 — find your way around the help --------------------------------
# 
# Use the help system to answer these without guessing.
# 
?round
# What is the second argument of round() called?
round(3.14159, digits = ___)

?seq
# Produce the numbers 0, 5, 10, ..., 100 using the `by` argument
seq(from = 0, to = ___, by = ___)

# Produce exactly 5 evenly spaced numbers between 0 and 1
seq(from = 0, to = 1, length.out = ___)

# 
# 
# ---- Exercise 4 — the workspace and the data -----------------------------------
# 
rm(list = ls())

memclinic <- read.csv("data/___.csv")

str(memclinic)
dim(memclinic)
names(memclinic)
head(memclinic, ___)

ls()                     # what is in the workspace now?
summary(memclinic$___)   # summarise the MoCA scores

# 
# 
# ---- What to take away ---------------------------------------------------------
# 
# - `<-` makes a variable, `=` names an argument. They are not interchangeable.
# - Never compare decimals with `==`.
# - `ls()` shows your workspace, `rm(list = ls())` empties it.
# - Open the `.Rproj`; never write `setwd()` into a script.
# - When anything surprises you, run `str()` on it.
# 
# ---- Going further -------------------------------------------------------------
# 
# The [appendix](appendix.qmd) covers names and memory, environments and masking,
# `attach()`/`detach()`, saving and loading objects, and floating point in more
# detail.
