# 1 · Appendix — what R is actually doing
# Statistics for brain and cognitive sciences (CN2) -- 2026/27
# student script
#
# GENERATED FROM sessions/01-r-basics/appendix.qmd -- DO NOT EDIT THIS FILE.
# Edit the .qmd and re-render the website; this file is overwritten.
#
# Open the .Rproj in this folder first, so that "data/..." paths resolve.

# 
# Nothing here is examinable. It is here because the answer to "but where does
# that number actually come from?" is worth having written down.
# 
# ---- Names are not objects -----------------------------------------------------
# 
# The lecture slides make a point that sounds abstract and turns out to be
# practical: a name does not contain a value, it *points* to one.
# 
# library(lobstr)
# 
# x <- c(1, 2, 3)
# y <- x
# obj_addr(x); obj_addr(y)     # the SAME address: one object, two labels
# 
# y[1] <- 99
# obj_addr(x); obj_addr(y)     # now different: R copied on modify
# x                            # x is untouched

# 
# This is why assigning a data frame to a second name costs nothing until you
# change one of them, and why R rarely surprises you by altering something you did
# not mean to alter.
# 
# `install.packages("lobstr")`. The chunks above and below are not run when this
# page is built, so a missing package cannot break anything.
# 
# ---- The professor's `info()` function -----------------------------------------
# 
# You will meet this in the lecture script `Regression1.R`, inside a block marked
# `### nerd mode on ###`. It is reproduced here so that it is recognition rather
# than confusion when it appears:
# 
# info <- function(x) {
#   return(list(
#     is_obj      = is.object(x),
#     obj_type    = sloop::otype(x),
#     R_type      = typeof(x),
#     obj_class   = class(x),
#     address_mem = lobstr::obj_addr(x),
#     size        = lobstr::obj_size(x),
#     SEXP_C      = lobstr::sxp(x)))
# }
# 
# info(c(1, 2, 3))

# 
# It answers, in one call, every question you can ask about what an object *is*.
# 
# ---- `typeof()`, `class()` and `mode()` ----------------------------------------
# 
# Three functions that look like they should agree, and do not.
# 
typeof(1L);  class(1L)
typeof(1);   class(1)
typeof("a"); class("a")
typeof(TRUE)

# 
# `typeof()` is how the value is stored in memory. `class()` is what R's
# statistical machinery treats it as, which is the one that decides how `summary()`
# or `plot()` will behave. A number typed without an `L` is a double, not an
# integer — `class(1)` is `"numeric"`.
# 
m <- lm(mpg ~ wt, data = mtcars)
class(m)
typeof(m)

# 
# A fitted model is *a list* that R has labelled `"lm"`, and that label is the
# entire reason `summary(m)` prints a regression table rather than a list dump.
# 
# ---- Floating point, properly --------------------------------------------------
# 
# Practical 1 showed that `sqrt(2)^2 == 2` is `FALSE`. Here is the machinery.
# 
print(sqrt(2)^2, digits = 22)
0.1 + 0.2 == 0.3
print(0.1 + 0.2 - 0.3, digits = 22)
.Machine$double.eps

# 
# Computers store numbers in binary with finite precision, and 0.1 has no exact
# binary representation any more than 1/3 has an exact decimal one. Three ways to
# compare safely:
# 
all.equal(0.1 + 0.2, 0.3)          # TRUE, with a tolerance
isTRUE(all.equal(0.1 + 0.2, 0.3))  # use this in an if()
dplyr::near(0.1 + 0.2, 0.3)        # the tidyverse version
identical(0.1 + 0.2, 0.3)          # exact: FALSE

# 
# ---- Integer division and remainder --------------------------------------------
# 
17 %/% 5     # how many whole 5s
17 %% 5      # what is left over

# 
# One genuine use — binning ages into decades:
# 
ages <- c(67, 72, 81, 79, 64)
(ages %/% 10) * 10

# 
# ---- Workspaces, files, and what `rm(list = ls())` does ------------------------
# 
# getwd()              # where am I
# list.files()         # what is here
# list.files("data")
# 
# x <- 1; y <- 2
# ls()                 # what is in the workspace
# rm(x)                # remove one thing
# rm(list = ls())      # remove EVERYTHING

# 
# Every lecture script in this course opens with `rm(list = ls())`. It is
# reasonable at the top of a script *you* are running from the beginning. It is
# rude in a script you hand to someone else, because it deletes their work without
# asking.
# 
# ---- Saving objects ------------------------------------------------------------
# 
# saveRDS(patients, "patients.rds")   # one object
# patients <- readRDS("patients.rds")
# 
# save(x, y, file = "two-things.RData")   # several, with their names
# load("two-things.RData")

# 
# `saveRDS()`/`readRDS()` stores one object and you choose the name when you read
# it back; `save()`/`load()` stores names as well, and `load()` drops them into
# your workspace whether or not something is already called that.
# 
# Last year's course folder contained files named `R3-group1` and `R4-MLR` with
# **no extension** — they were RDS files, and nothing on the outside said so. The
# rule in these materials is that data is a `.csv` with its extension visible.
# 
# ---- Environments and masking --------------------------------------------------
# 
# The professor describes environments as "bags of names". When you load a
# package, its bag goes on top of the pile:
# 
search()

# 
# If two packages define the same function, the one loaded **last** wins, and R
# tells you so with a `masked from` message. `MASS::select` and `dplyr::select`
# are the classic collision in this course.
# 
# library(MASS)
# library(dplyr)       # "The following object is masked from 'package:MASS': select"
# select(mtcars, mpg)  # which select is this?
# dplyr::select(mtcars, mpg)   # no ambiguity

# 
# The `pkg::fun()` form is the cure, and it is why these materials write
# `psych::describe()` and `car::ncvTest()` rather than loading those packages.
# 
# ---- `attach()` and `detach()` -------------------------------------------------
# 
# `attach()` puts a data frame's columns on the search path so you can name them
# directly. The slides teach it, so here it is:
# 
# attach(mtcars)
# mpg           # works, without mtcars$
# ls()          # but mpg is NOT in your workspace
# search()      # mtcars is on the path instead
# detach(mtcars)
# mpg           # now an error

# 
# The professor's warning is the important part: **always remember to `detach()`
# when you are done.** The failure mode is attaching the same data frame twice, or
# attaching one and then modifying the original — the attached copy does not
# change with it, and you end up analysing data you think you have updated.
# 
# ---- Writing your own function -------------------------------------------------
# 
hypo <- function(a, b) {
  c = sqrt(a^2 + b^2)
  return(c)
}

hypo(3, 4)
hypo(a = 3, b = 4)

# 
# Note the assignment discipline: `<-` binds the function to the name `hypo`, and
# `=` names arguments at the call site. Three parts make up any function:
# 
formals(hypo)
body(hypo)

# 
# Arguments can have defaults:
# 
z_score <- function(x, na.rm = TRUE) {
  (x - mean(x, na.rm = na.rm)) / sd(x, na.rm = na.rm)
}
round(z_score(c(10, 12, 14, 16, 100)), 2)

# 
# Write the obvious version of `mean()` and watch it fail quietly:
# 
my_mean <- function(x) sum(x) / length(x)

my_mean(c(1, 2, 3))
my_mean(c(1, NA, 3))    # NA, and it will not tell you why

# 
# The same lesson as practical 3, where `mean(2, 3, 10)` returns `2`: the
# function did exactly what you wrote, which was not what you meant.
# 
# ---- `seq_along()`, not `1:length(x)` ------------------------------------------
# 
x <- numeric(0)      # an empty vector
1:length(x)          # counts DOWN from 1 to 0
seq_along(x)         # empty, as it should be

# 
# A loop written `for (i in 1:length(x))` runs twice on an empty vector, indexing
# positions 1 and 0. `seq_along()` runs zero times. This is why the lecture slides
# insist on it.
